export const TRANSLATIONS_EN = {
    'allActivity': 'All Activity',
    'profile': 'Profile',
    'inboxScreenNotSignedInMessage': 'Messages and notifications will appear here',
    'signUpForAccount': 'Sign up for an account',
    'signUp': 'Sign up',
    'home': 'Home',
    'discover': 'Discover',
    'create': 'Create',
    'inbox': 'Inbox',
    'me': 'Me',
    'settingsAndPrivacy': 'Settings and Privacy',
    'account': 'ACCOUNT',
    'myAccount': 'My account',
    'privacy': 'Privacy',
    'contentAndActivity': 'CONTENT & ACTIVITY',
    'appLanguage': 'App language',
    'contentPreferences': 'Content preferences',
    'cacheAndCellularData': 'CACHE & CELLULAR DATA',
    'freeUpSpace': 'Free up space',
    'dataSaver': 'Data Saver',
    'support': 'SUPPORT',
    'reportProblem': 'Report a Problem',
    'helpCenter': 'Help Center',
    'safetyCenter': 'Safety Center',
    'creatorPortal': 'Creator Portal',
    'about': 'ABOUT',
    'communityGuidelines': 'Community Guidelines',
    'termsOfService': 'Terms of Service',
    'privacyPolicy': 'Privacy Policy',
    'copyrightPolicy': 'Copyright Policy'
};
