export const TRANSLATIONS_EN = {
    'allActivity': 'All Activity',
    'profile': 'Profile',
    'inboxScreenNotSignedInMessage': 'Messages and notifications will appear here',
    'signUpForAccount': 'Sign up for an account',
    'signUp': 'Sign up',
    'home': 'Home',
    'discover': 'Discover',
    'create': 'Create',
    'inbox': 'Inbox',
    'me': 'Me',
    'settingsAndPrivacy': 'Settings and Privacy',
    'account': 'ACCOUNT',
    'myAccount': 'My account',
    'privacy': 'Privacy',
    'contentAndActivity': 'CONTENT & ACTIVITY',
    'appLanguage': 'App language',
    'contentPreferences': 'Content preferences',
    'cacheAndCellularData': 'CACHE & CELLULAR DATA',
    'freeUpSpace': 'Free up space',
    'dataSaver': 'Data Saver',
    'support': 'SUPPORT',
    'reportProblem': 'Report a Problem',
    'helpCenter': 'Help Center',
    'safetyCenter': 'Safety Center',
    'creatorPortal': 'Creator Portal',
    'about': 'ABOUT',
    'communityGuidelines': 'Community Guidelines',
    'termsOfService': 'Terms of Service',
    'privacyPolicy': 'Privacy Policy',
    'copyrightPolicy': 'Copyright Policy',
    'english': 'English',
    'signUpForTiktok': 'Sign up for TikTok',
    'signUpSubText': 'Create a profile, follow other accounts, make your own videos, and more.',
    'usePhoneOrEmail': 'Use phone or email',
    'useFacebook': 'Continue with Facebook',
    'useGoogle': 'Continue with Google',
    'useTwitter': 'Continue with Twitter',
    'signUpTermsAndPrivacy': 'By signing up, you agree to our Terms of Service and acknowledge that you have read our Privacy Policy to learn how we collect, use, and share your data.',
    'alreadyHaveAccount': 'Already have an account?',
    'logIn': 'Log in',
    'search': 'Search',
    'trending': 'Trending',
    'hash': 'hashtag',
    'music': 'sound',
    'following': 'Following',
    'followers': 'Followers',
    'likes': 'Likes',
    'follow': 'Follow'
};
