export const TRANSLATIONS_EN = {
    'allActivity': 'All Activity',
    'profile': 'Profile',
    'inboxScreenNotSignedInMessage': 'Messages and notifications will appear here',
    'signUpForAccount': 'Sign up for an account',
    'signUp': 'Sign up',
    'home': 'Home',
    'discover': 'Discover',
    'create': 'Create',
    'inbox': 'Inbox',
    'me': 'Me',
    'settingsAndPrivacy': 'Settings and Privacy',
    'account': 'ACCOUNT',
    'myAccount': 'My account',
    'privacy': 'Privacy',
    'contentAndActivity': 'CONTENT & ACTIVITY',
    'appLanguage': 'App language',
    'contentPreferences': 'Content preferences',
};
